apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ecommerce.fullname" . }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ecommerce.name" . }}
        app.kubernetes.io/component: backend
        {{- include "ecommerce.labels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: {{ .Values.backend.env.FLASK_ENV | quote }}

            - name: POSTGRES_HOST
              value: {{ include "ecommerce.fullname" . }}-postgres

            - name: POSTGRES_PORT
              value: {{ .Values.backend.env.POSTGRES_PORT | quote }}

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: POSTGRES_DB
            
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
