apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce.fullname" . }}-postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
