{{- if .Values.postgres.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.secrets.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.secrets.POSTGRES_PASSWORD | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.secrets.POSTGRES_DB | b64enc | quote }}
{{- end }}
